# Generated by Django 5.0.2 on 2024-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_crop_notes_alter_crop_yield_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('livestock_id', models.AutoField(primary_key=True, serialize=False)),
                ('livestock_type', models.CharField(max_length=255)),
                ('livestock_breed', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('health_status', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
    ]
