# Generated by Django 5.0.2 on 2024-03-25 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_livestock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='harvesting_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 25), null=True),
        ),
    ]
