# Generated by Django 5.0.2 on 2024-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_crop_harvesting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='harvesting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
