# Generated by Django 5.0.2 on 2024-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_sale_notes_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(max_length=25),
        ),
    ]
